# Generated by Django 4.1.5 on 2023-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_contact_phone_alter_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
